# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js runtime as a parent image
FROM node:22.12-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package.json /app

# Install any needed packages specified in package.json
RUN --mount=type=cache,target=/root/.npm npm install --ignore-scripts

# Copy the rest of the application code
COPY . /app

# Build the application
RUN npm run build

# Create a new image from the node:alpine image for release
FROM node:22-alpine AS release

# Set the working directory in the release image
WORKDIR /app

# Copy the build artifacts from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/node_modules /app/node_modules

# Specify environment variables required by the app
ENV NODE_ENV=production

# Run the MCP server
ENTRYPOINT ["node", "dist/index.js"]
